backend = "kmeans"

color_space = "lab"

threshold = 18

palette = "dark16"

[templates]

kitty = { src = "colors-kitty.conf", dst = "~/.config/kitty/colors.conf" }

ghostty = { src = "colors-ghostty", dst = "~/.config/ghostty/colors" }

hypr = { src = "colors-hypr.conf", dst = "~/.config/hypr/colors.conf" }

waybar = { src = "colors-waybar.css", dst = "~/.config/waybar/colors.css" }

rofi = { src = "colors-rofi.rasi", dst = "~/.config/rofi/colors.rasi" }

wlogout = { src = "colors-wlogout.css", dst = "~/.config/wlogout/colors.css" }

swaync = { src = "colors-swaync.css", dst = "~/.config/swaync/colors.css" }

kde = { src = "colors-kde.colors", dst = "~/.local/share/color-schemes/Wallust.colors" }
